---
name: Module-License-Report
version: 0.01
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: Determine the license of a module
license: perl
requires:
  CPANPLUS: 0.051
  File::Slurp: 9999.09
  File::Spec: 0
  YAML: 0
  perl: 5.6.0
recommends:
  Module::CoreList: 2.00
  Module::Depends: 0
build_requires:
  Test::MockObject: 0
  Test::More: 0
provides:
  Module::License::Report:
    file: lib/Module/License/Report.pm
    version: 0.01
  Module::License::Report::CPANPLUS:
    file: lib/Module/License/Report/CPANPLUS.pm
    version: 0.01
  Module::License::Report::CPANPLUSModule:
    file: lib/Module/License/Report/CPANPLUSModule.pm
    version: 0.01
  Module::License::Report::Object:
    file: lib/Module/License/Report/Object.pm
    version: 0.01
generated_by: Module::Build version 0.2611
